# Generated by Django 5.2.14 on 2026-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_ai_goal_course_is_ai_generated_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ai_goal',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
