# Generated by Django 5.2.14 on 2026-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=100),
        ),
    ]
