# Generated by Django 5.2.14 on 2026-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='strength_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='weakness_analysis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
